# Generated by Django 4.1.1 on 2023-05-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
